### ISSUE TITLE
wakeUpDyno is not defined

### ISSUE THREAD

**Issue by lsaether** [daaniiieel/bridgeCross#1]
How can I get this working on Heroku? I set up all the env vars but it doesn't start automatically.

I start a bash shell in my dyno and try to run `npm run start` and I get the following error:

![image](https://user-images.githubusercontent.com/25539605/102587021-76e38500-410b-11eb-84f3-12fb7cdaeb22.png)

Any tips?

**Comment by MuhammedTaha02** [comment]
+1
I have this problem

![image](https://user-images.githubusercontent.com/62564400/102619779-09a51380-414e-11eb-80a5-fab6fe69ca78.png)
